### ISSUE TITLE
Internal Server Error with upload (urbs)

### ISSUE THREAD

**Issue by sonercandas** [open-modex/oedatamodel_api#10]
Hi Hendrik, with the attached output data i receive an` Internal Server Error` when i cross  "Adapt foreign keys (foreign keys are automatically set)", and "`"{\"reason\": \"Action violates constraint oed_scenario_output_pkey. Failing row was (25, base, {'DE': ['BB', 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']}, 2016, None, ['The scenario depicts the electricity sector in Germany. It is divided into 18 nodes, 16 nodes as federal states and 2 offshore nodes. Germany's neighbouring countries are not considered.'])\"}`"" when that setting is not crossed.

Could you please have a quick look and see if you can spot where I might have made a mistake? Thanks!

[Urbs.zip](https://github.com/open-modex/oedatamodel_api/files/6397962/Urbs.zip)

**Comment by henhuy** [comment]
Hey @sonercandas ,
first: Adapt FKs **must** be activated, otherwise this cannot work.
second: When uploading your data with "adapt FKs" checked, I get following error:
`"{\"reason\": \"column \\\"series\\\" is of type double precision[] but expression is of type text[]\"}"`
and this is because timeseries column `series` is of type `array(float)` but you are inserting text (at least in your last 5 rows of timeseries.csv)...
Ths is casuing the error!

**Comment by sonercandas** [comment]
Hi @henhuy, even after removing the rows that have strings instead of numbers in timeseries (that was a mistake from my side with my mapping), I get the Internal Server Error... 

How did you actually receive that error message that you mentioned?: "{\"reason\": \"column \\\"series\\\" is of type double precision[] but expression is of type text[]\"}" I just get Internal Server Error, which is not too helpful if I want to debug on my own :/

Here is the data I want to upload right now: [Urbs2.zip](https://github.com/open-modex/oedatamodel_api/files/6404477/Urbs2.zip)

**Comment by henhuy** [comment]
For me it just worked out f the box (No changes)! => ID 35 
Snapshot of my upload:.
![grafik](https://user-images.githubusercontent.com/17476051/116690287-77453400-a9b9-11eb-9b0c-52ed9388b260.png)

**Comment by sonercandas** [comment]
Ah, it slipped from my mind that I have to use the Mapping "normalize_output" (i left it always empty before). Thanks @henhuy !

**Comment by henhuy** [comment]
but good to know that I shoud improve error mesages!
