### ISSUE TITLE
Validation of oedatamodel field dtypes

### ISSUE THREAD

**Issue by chrwm** [open-modex/oedatamodel_api#14]
The validation of the OEP during the upload of a datapackage prevents successful changes of the dtypes per field.
In the oed_scenario.csv, this prevents the current dtype "integer" in the field 'year' from being changed to another dtype. 
However, this results in the scenarios only having one entry for a single year. Multiple years cannot be inserted into the field, e.g. 2016,2030,2050.

Is changing the dtype of the 'year' field in oed_scenario.csv an option to allow multiple years to be entered?

**Comment by henhuy** [comment]
> Is changing the dtype of the 'year' field in oed_scenario.csv an option to allow multiple years to be entered?

No, this is not an option as the type is fix in the OEP.

The upload process is as follows:
- Datapackage from zip file is build
- Datapackage is validated (checks consistency within the datapackage - here you could (be you shouldn't) change type of year to string and the validation would work!)
- If checked, mapping will be performed on uploaded data
- if checked FKs are adapted to data
- Resulting data is validated (second validation!) against OEP datapackage format (here is, where your validation fails, as year column in OEP is integer not string!)
- if datapackage is valid, data is uploaded to related tables in OEP

Thus, changing type of column year had to be done in OEP first.
**BUT** I don't know if we should change column type at this point, as many data has been uploaded so far.
Additionally, I somehow remember @gnn argumenting for year to be integer (I think, I suggested list-of-int in the past?! - can't quite remember)
