### ISSUE TITLE
Foreign-key-error

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/oedatamodel_api#15]
Hi, 

When I try to upload my newest results, I all of a sudden get this 'Foreign-key-error' and I have no idea where it comes from or what it is or how to handle it. Do you have any hints on how to handle it? 
You can find the zip folders that I try to upload here: 
https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Balmorel/ID34&fileid=1088086 

best, 

Stefanie

**Comment by henhuy** [comment]
In scalar CSV foreign key scenario_id is set to 34 for all rows, but scenario in scenario CSV has ID 1.
Therefore you get an foreign-key error (TS seems correct).
To solve this, you should simply set scenario_id = 1 in all scalar rows.

**Comment by StefanieBuchholz** [comment]
Ah alright, I actually had scenario_id = 1 and got errors, so I looked into the files of Urbs and saw they were using scenario_id = 34 så I addapted - however it seems I made the problems even bigger. Anyway, I am now back to scenario_id = 1 and I then again get the original error again, which is:


error on upload | "{\"reason\": \"Action violates constraint oed_scenario_output_pkey. Failing row was (1, base, {'DE': ['BB', 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']}, 2050, None, ['The scenario depicts the electricity sector in Germany. It is divided into 18 nodes, 16 nodes as federal states and 2 offshore nodes. Germany's neighbouring countries are not considered.'])\"}"
-- | --


Do you then have an idea what that is about? 
Currently 2050 is updated at: https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Balmorel/ID34&fileid=1088086 
and the 2050 zip file is the one producing the above error. Year 2016 and 2030 are getting updated with the scenario_id

**Comment by henhuy** [comment]
I think this is because you did not activate "Adapt foreign keys".
But nevertheless, if you do so - you will get two simple errors regarding your scalars:
![grafik](https://user-images.githubusercontent.com/17476051/121199792-80a4a480-c873-11eb-8565-a838617b69f0.png)
as there is unvalid data in row 310 and 311 (ie. year is "NA", not integer)...
Hope that helps!

**Comment by StefanieBuchholz** [comment]
I corrected that, but maybe I messed up the upload sorry for this! Anyway, I just tried to upload again and this time  "Adapt foreign keys" and now it seemed to work! So thanks a lot :D 
To be honest, I feel that I on and off get different errors and I never really find out when they come and how they are solved. But as it seems to work now, I am happy :p Thanks again!
