### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by fateme-rwth** [open-modex/oedatamodel_api#8]
I could successfully upload for genesys with ID 18 thanks for getting back to our issues by email. however I get the following warnings. I am wondering what they mean. 

warnings": [
"Metadata for OEP table 'model_draft.oed_scenario_output' not found or invalid. Thus, data could not be validated against table format",
"Metadata for OEP table 'model_draft.oed_data_output' not found or invalid. Thus, data could not be validated against table format",
"Metadata for OEP table 'model_draft.oed_scalar_output' not found or invalid. Thus, data could not be validated against table format",
"Metadata for OEP table 'model_draft.oed_timeseries_output' not found or invalid. Thus, data could not be validated against table format"
]

**Comment by henhuy** [comment]
Nice!
Those warnings can be neglected. They only say that metadata in OEP is not correct. 
But as your data could be uploaded, everything is okay.
