### ISSUE TITLE
timeseries issue (timestamps)

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/oedatamodel_api#9]
Hi Hendrik, 

I have an issue with the timestamps in the timeseries file. I am really trying to make the file look exactly like the one you fixed for me (the one in step 4 of your walkthrough), however it is not working. My zip file including the timeseries file causing errors is placed here: 

https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Balmorel/ID25&fileid=1052713

Additionally I also added the timeseries file outside of the zip together with the timeseries file that you fixed for me last time (from step 4) called '_NoError'. If I replace the timeseries file in the zip with the '_NoError' timeseries file, then it is uploaded without errors. I also uploaded a picture of the first error I get. 

Do you have an idea of what the error is? 

best regards, 

Stefanie

**Comment by henhuy** [comment]
Sorry for late answer.
The date format is different!
No error: `2016-01-01 00:00:00`
Error: `2016-01-01 00:00` (seconds are missing)
In order to fix this, you have two options:
- change date format of `timeindex_start` and `timeindex_end` in `datapackage.json` (see also https://github.com/open-modex/oedatamodel_api/issues/7#issuecomment-820247384)
- add "seconds" to all entries in timeseries.csv (start and end column)

**Comment by jh-RLI** [comment]
Side note: It would be very good to collect the user feedback/issues [here](https://github.com/OpenEnergyPlatform/oedatamodel/issues/45). I will then review the list and update the [oedatamodel ](https://github.com/OpenEnergyPlatform/oedatamodel)documentation and examples.

**Comment by StefanieBuchholz** [comment]
Hi Hendrik @henhuy, 

As mentioned in our WebCo last time, i am challenged by the Json view not being activated and therefore it is hard for me to see what errors I may have. Can you check if you can upload my .zip file and if you encounter the same thing? 

I have placaed my new .zip folder here: https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Balmorel/ID31&fileid=1069695 (ID31)

in this place you also find a picture showing what I see when the page is done loading. Normally the page is loading and when it is done the page changes to the nice Json view - but with this .zip file it just loads for several minutes and then stops. 

/Stefanie

**Comment by henhuy** [comment]
Hey @StefanieBuchholz,
upload just worked for me (=ID37).
Maybe you made same mistake as Soner (wrong upload mapping)?:
![grafik](https://user-images.githubusercontent.com/17476051/117431374-70727000-af29-11eb-9a94-b06c3e37b03a.png)

**Comment by henhuy** [comment]
And I can see JSON as usual... maybe a browser issue??

**Comment by StefanieBuchholz** [comment]
Ah okay, that is just perfect if it works! Thank you very much! I will then update the current Balmorel ID to 31. 

Maybe it is just a browser error for me then - a bit annoying, but if it only do it when I have no errors then fine :p 
I actually did not try to upload it, I just tried to show it witout uploading. However, if I see this again, can I then try to upload it, and then this will tell me if I had any errors? But my concern is then if I mess something up by uploading an ID with errors - is that a problem?

**Comment by henhuy** [comment]
ID is 37!
No problem if upload is not valid - right now there are several broken uploads.
That is why we gather valid IDs in our issue.

**Comment by StefanieBuchholz** [comment]
I might be a bit confused now, but the upload i just made was made based on Balmorel model runs on the data collected from:
https://modex.rl-institut.de/scenario/id/31?source=modex&mapping=regions&output=csv
So in here I specify ID31 - is that then not the ID of my results?

**Comment by StefanieBuchholz** [comment]
@henhuy, Sorry i now see that we are referring to different IDs. I just saw that the issue I once made with the ID of the current data results was closed due to this new one - but here we refer to the number our results has in the Dashboard! I correct to ID37 :)
